services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.36.0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      ENABLE_MODULES: "text2vec-openai"
      WEAVIATE_ENABLE_UI: "true"
      ENABLE_CORS: "true"             # allow Studio to connect from host
      WEAVIATE_HOST: "localhost"      # fixes redirect to /v1 
      
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_KEY}
      AZURE_OPENAI_APIKEY: ${AZURE_OPENAI_KEY}
      AZURE_OPENAI_API_BASE: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_TYPE: azure
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"

    env_file:
      - .env